#!/bin/bash

set -euo pipefail

echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends \
 && echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends \
 && DEBIAN_FRONTEND=noninteractive apt-get update -qq \
 && DEBIAN_FRONTEND=noninteractive apt-get -qq -y --no-install-recommends install \
    $@ \
 && apt-get auto-remove -qq -y \
   && apt-get clean \
   && rm -rf /var/lib/apt/lists/*
